name: Chunklock
version: '${project.version}'
main: me.misleaded.chunklock.Chunklock
api-version: 1.21
authors: [ misleaded, Fedaykin ]
description: Chunks can now only be unlocked with randomly generated items.
commands:
  start:
    description: Begins the Chunklock challenge
    usage: /start Optional(<x> <z>)
  unlock:
    description: Unlocks the chunk at specified coordinates
    usage: /unlock <x> <z> Optional(<world>)